version: 0.2

env:
  variables:
    ENV: "dev"
    TF_IN_AUTOMATION: "true"
    TF_VERSION: "1.12.2"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - curl -fsSL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip -d /usr/local/bin
      - terraform version

  pre_build:
    commands:
      - cd 01-Infra/environments/${ENV}
      - terraform init -backend=false

  build:
    commands:
      - terraform fmt -check -recursive ../../
      - terraform validate
      - terraform plan -out=tfplan

artifacts:
  files:
    - 01-Infra/environments/${ENV}/tfplan
