version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: "true"
    TF_VERSION: "1.12.2"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - curl -fsSL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip -d /usr/local/bin
      - terraform version

  pre_build:
    commands:
      - echo "Environment - $ENV"
      - echo "Actions - $ACTIONS"
      - cd 01-Infra/environments/$ENV
      - echo "Cleaning up any existing locks..."
      - aws s3 rm s3://demo-eks-manoj-shopcase/envs/dev/network/terraform.tfstate.tflock --ignore-error || true

  build:
    commands:
      - terraform init -input=false
      - terraform plan -input=false -out=tfplan -lock=false
      - echo "Action to execute - $ACTIONS"
      - |
        if [ "$ACTIONS" = "apply" ]; then
          terraform apply -input=false -auto-approve tfplan
        elif [ "$ACTIONS" = "destroy" ]; then
          terraform destroy -input=false -auto-approve -lock=false
        else
          echo "Invalid ACTIONS value: $ACTIONS"
          echo "Valid values: apply, destroy"
          exit 1
        fi

artifacts:
  files:
    - "**/*"
<<<<<<< HEAD
  name: terraform-cd-$ENV-$ACTIONS
=======
  name: terraform-cd-$ENV-$ACTIONS
>>>>>>> 60c4a91 (application deploy files)
